services:
  - type: web
    name: byblos-atelier-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # You'll add more environment variables in the Render dashboard
    plan: free
